# Generated by Django 2.2.5 on 2021-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('username', models.TextField()),
                ('poecontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('release_id', models.IntegerField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('poecontent', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.TextField()),
                ('poecontent', models.TextField()),
                ('username', models.TextField()),
                ('goodnum', models.IntegerField(default=0)),
                ('mywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('city', models.CharField(default='unknown', max_length=20, verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
